// job-portal-client-side/src/components/profile/description-profile/LinkAccount.jsx
import { Button, Form, Input, Modal, message } from "antd";
import { useState, useEffect } from "react";
import { LinkIcon, CheckCircleIcon } from "@heroicons/react/24/outline";
import Api from "../../../services/Api";
import { getUserSession } from "../../../utils";

const LinkAccount = ({ open, setOpen }) => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [profileLoading, setProfileLoading] = useState(false);
  const [userProfile, setUserProfile] = useState(null);
  const [isLinked, setIsLinked] = useState(false);

  const getUserProfile = async () => {
    setProfileLoading(true);
    try {
      const user = await getUserSession();
      if (user.role === "job_seeker") {
        const { data } = await Api.get("/profile/my");
        setUserProfile(data);
        setIsLinked(data.user.lmsUserId !== null);
      }
    } catch (error) {
      console.error("Error fetching user profile:", error);
      message.error("Failed to fetch profile information");
    } finally {
      setProfileLoading(false);
    }
  };

  useEffect(() => {
    if (open) {
      getUserProfile();
    }
  }, [open]);

  const handleCancel = () => {
    setOpen(false);
    form.resetFields();
  };

  const handleFinish = async (values) => {
    setLoading(true);
    try {
      const response = await Api.post("/lms/link-account", {
        email: values.email,
        password: values.password,
      });

      message.success("Account linked successfully!");
      // Refresh profile data after successful linking
      await getUserProfile();
      handleCancel();
    } catch (error) {
      const errorMessage = error?.response?.data?.message || "Failed to link account. Please try again.";
      message.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleUnlink = async () => {
    setLoading(true);
    try {
      await Api.post("/lms/unlink-account");
      message.success("Account unlinked successfully!");
      await getUserProfile();
    } catch (error) {
      const errorMessage = error?.response?.data?.message || "Failed to unlink account. Please try again.";
      message.error(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const renderLinkedStatus = () => (
    <div className="text-center py-8">
      <CheckCircleIcon className="h-16 w-16 text-green-500 mx-auto mb-4" />
      <h3 className="text-lg font-semibold text-gray-800 mb-2">
        Account Successfully Linked
      </h3>
      <div className="mb-4 p-4 bg-green-50 rounded-lg">
        <p className="text-sm text-green-700">
          Your Job Portal account is successfully linked with the LMS system.
        </p>
        {userProfile?.user?.lmsLinkedAt && (
          <p className="text-xs text-green-600 mt-2">
            Linked on: {new Date(userProfile.user.lmsLinkedAt).toLocaleString()}
          </p>
        )}
      </div>
      <div style={{ textAlign: "center", marginTop: 24 }}>
        <Button
          onClick={handleCancel}
          style={{
            width: 120,
            height: 40,
            borderRadius: 12,
            borderColor: "#BBB",
            marginRight: 8,
          }}
          disabled={loading}
        >
          <span className="font-medium text-[#232323]">Close</span>
        </Button>
        <Button
          danger
          style={{ 
            width: 120, 
            height: 40, 
            borderRadius: 12,
          }}
          onClick={handleUnlink}
          loading={loading}
        >
          <span className="font-medium">Unlink</span>
        </Button>
      </div>
    </div>
  );

  const renderLinkForm = () => (
    <>
      <div className="mb-4 p-4 bg-blue-50 rounded-lg">
        <p className="text-sm text-blue-700">
          Link your Job Portal account with the LMS system to access integrated features and sync your learning progress.
        </p>
      </div>

      <Form
        form={form}
        layout="vertical"
        requiredMark={true}
        onFinish={handleFinish}
        className="text-left"
      >
        <Form.Item
          name="email"
          label="LMS Email"
          rules={[
            { required: true, message: "Email cannot be empty!" },
            { type: "email", message: "Please enter a valid email address!" },
          ]}
        >
          <Input 
            style={{ borderRadius: 12, height: 56 }} 
            placeholder="Enter your LMS email address"
          />
        </Form.Item>

        <Form.Item
          name="password"
          label="LMS Password"
          rules={[
            { required: true, message: "Password cannot be empty!" },
            { min: 6, message: "Password must be at least 6 characters!" },
          ]}
        >
          <Input.Password 
            style={{ borderRadius: 12, height: 56 }} 
            placeholder="Enter your LMS password"
          />
        </Form.Item>

        <div style={{ textAlign: "center", marginTop: 24 }}>
          <Button
            onClick={handleCancel}
            style={{
              width: 120,
              height: 40,
              borderRadius: 12,
              borderColor: "#BBB",
              marginRight: 8,
            }}
            disabled={loading}
          >
            <span className="font-medium text-[#232323]">Cancel</span>
          </Button>
          <Button
            type="primary"
            style={{ 
              width: 120, 
              height: 40, 
              borderRadius: 12,
              backgroundColor: "#1890ff"
            }}
            htmlType="submit"
            loading={loading}
          >
            <span className="font-medium">Link Account</span>
          </Button>
        </div>
      </Form>
    </>
  );

  return (
    <Modal
      title={
        <div style={{ display: "flex", alignItems: "center" }}>
          {isLinked ? (
            <CheckCircleIcon className="h-6 w-6 mr-3 text-green-600" />
          ) : (
            <LinkIcon className="h-6 w-6 mr-3 text-blue-600" />
          )}
          <span>{isLinked ? "Account Status" : "Link Account"}</span>
        </div>
      }
      centered
      open={open}
      onCancel={handleCancel}
      width={500}
      maskClosable={false}
      destroyOnClose={true}
      footer={null}
      style={{
        borderRadius: 24,
        overflow: "hidden",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", marginBottom: 16 }}>
        <hr
          style={{
            flex: 1,
            borderColor: "#E9E9E9",
            margin: 3,
            borderWidth: "1px",
          }}
        />
      </div>

      {profileLoading ? (
        <div className="text-center py-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="text-gray-500 mt-4">Loading account status...</p>
        </div>
      ) : (
        isLinked ? renderLinkedStatus() : renderLinkForm()
      )}
    </Modal>
  );
};

export default LinkAccount;

// lms-client-side/src/pages/role/student/dashboard/settings/akun/LinkAccount.vue
<script setup>
import { ref, watch } from "vue";
import axios from "axios";

const props = defineProps({
  open: Boolean,
});

const emit = defineEmits(["close", "link-success"]);

const loading = ref(false);
const email = ref("");
const password = ref("");
const errorMessage = ref("");

const handleCancel = () => {
  emit("close");
};

const handleFinish = async () => {
  loading.value = true;
  errorMessage.value = "";
  try {
    await axios.post("/link-job-portal", {
        email: email.value,
        password: password.value,
      }, {
        headers: { Authorization: `Bearer ${localStorage.getItem("token")}` },
      }
    );
    emit("link-success");
    handleCancel();
  } catch (error) {
    errorMessage.value = error.response?.data?.message || "Failed to link account. Please try again.";
  } finally {
    loading.value = false;
  }
};

watch(
  () => props.open,
  (newVal) => {
    if (!newVal) {
      email.value = "";
      password.value = "";
      errorMessage.value = "";
    }
  }
);
</script>

<template>
  <div v-if="open" class="modal-backdrop fade show"></div>
  <div v-if="open" class="modal fade show d-block" tabindex="-1" @click.self="handleCancel">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content rounded-4 border-0">
        <div class="modal-header border-bottom-0">
          <h5 class="modal-title d-flex align-items-center">
            <i class="bi bi-link-45deg text-primary me-2 fs-4"></i>
            Link Job Portal Account
          </h5>
          <button type="button" class="btn-close" @click="handleCancel"></button>
        </div>
        <div class="modal-body p-4">
          <form @submit.prevent="handleFinish">
            <p class="text-muted">
              Link your LMS account with the Job Portal system to access
              integrated features.
            </p>
            <div v-if="errorMessage" class="alert alert-danger fs-14 py-2">
              {{ errorMessage }}
            </div>
            <div class="mb-3">
              <label for="jp-email" class="form-label fs-14">Job Portal Email</label>
              <input type="email" class="form-control h-48" id="jp-email" v-model="email" placeholder="Enter your Job Portal email" required />
            </div>
            <div class="mb-3">
              <label for="jp-password" class="form-label fs-14">Job Portal Password</label>
              <input type="password" class="form-control h-48" id="jp-password" v-model="password" placeholder="Enter your Job Portal password" required />
            </div>
            <div class="d-grid mt-4">
              <button type="submit" class="btn btn-primary h-48" :disabled="loading">
                <span v-if="loading" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                <span v-else>Link Account</span>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.modal {
  background-color: rgba(0, 0, 0, 0.5);
}
.modal-dialog {
  max-width: 500px;
}
</style>
